<?xml version='1.0' encoding="UTF-8"?>


<!DOCTYPE archivo_De_empresa [
<!ELEMENT archivo_De_empresa (operaciones+)>
<!ELEMENT operaciones (venta | compra)+>
<!ELEMENT venta (titulo+, cantidad, entregado?, importe)>
<!ELEMENT compra (titulo+, proveedor, fecha)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT entregado (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ATTLIST importe moneda CDATA #REQUIRED>
<!ELEMENT proveedor (#PCDATA)>
<!ELEMENT fecha (dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
]>


<archivo_De_empresa>

    <operaciones>
        <venta>
            <titulo>Libro 1</titulo>
            <titulo>Libro 2</titulo>
            <cantidad>15</cantidad>
            <entregado>si</entregado>
            <importe moneda='euros'>50</importe>
        </venta>

        <compra>
            <titulo>Libro 3</titulo>
            <titulo>Libro 4</titulo>
            <proveedor>Diego</proveedor>
            <fecha>
                <dia>15</dia>
                <mes>05</mes>
                <anio>2024</anio>
            </fecha>
        </compra>
    </operaciones>

    <operaciones>
        <venta>
            <titulo>Libro 8</titulo>
            <cantidad>10</cantidad>
            <entregado>no</entregado>
            <importe moneda='euros'>50</importe>
        </venta>

        <venta>
            <titulo>Libro 6</titulo>
            <titulo>Libro 14</titulo>
            <titulo>Libro 10</titulo>
            <cantidad>30</cantidad>
            <entregado>si</entregado>
            <importe moneda='euros'>150</importe>
        </venta>
    </operaciones>

    <operaciones>
        <compra>
            <titulo>Libro 10</titulo>
            <proveedor>Roger</proveedor>
            <fecha>
                <dia>05</dia>
                <mes>01</mes>
                <anio>2018</anio>
            </fecha>
        </compra>

        <compra>
            <titulo>Libro 5</titulo>
            <titulo>Libro 5</titulo>
            <proveedor>Diego</proveedor>
            <fecha>
                <dia>02</dia>
                <mes>10</mes>
                <anio>2020</anio>
            </fecha>
        </compra>

        <compra>
            <titulo>Libro 15</titulo>
            <titulo>Libro 20</titulo>
            <titulo>Libro 34</titulo>
            <proveedor>Diego</proveedor>
            <fecha>
                <dia>12</dia>
                <mes>01</mes>
                <anio>2023</anio>
            </fecha>
        </compra>
    </operaciones>

</archivo_De_empresa>
